from detransapp.manager.tipo_veiculo import TipoVeiculoManager
from detransapp.manager.tipo_infracao import TipoInfracaoManager
from detransapp.manager.infrator import InfratorManager
from detransapp.manager.especie import EspecieManager
from detransapp.manager.agente import AgenteManager
from detransapp.manager.veiculo import VeiculoManager
from detransapp.manager.uf import UFManager
from detransapp.manager.cidade import CidadeManager
from detransapp.manager.modelo import ModeloManager
from detransapp.manager.regiao import RegiaoManager
from detransapp.manager.infracao import InfracaoManager
from detransapp.manager.lei import LeiManager
from detransapp.manager.bloco import BlocoManager
from detransapp.manager.cor import CorManager
from detransapp.manager.categoria import CategoriaManager
from detransapp.manager.tipo_cancelamento import TipoCancelamentoManager
from detransapp.manager.dispositivo import DispositivoManager
from detransapp.manager.log_sincronizacao import LogSincronizacaoManager
from config_sinc import ConfigSincManager
from det import DETManager
