from detransapp.models.pessoa import Pessoa
from detransapp.models.agente import Agente
from detransapp.models.agente_login import Agente_login
from detransapp.models.bloco import Bloco
from detransapp.models.categoria import Categoria
from detransapp.models.uf import UF
from detransapp.models.cidade import Cidade
from detransapp.models.cor import Cor
from detransapp.models.dispositivo import Dispositivo
from detransapp.models.especie import Especie
from detransapp.models.infracao import Infracao
from detransapp.models.infrator import Infrator
from detransapp.models.lei import Lei
from detransapp.models.medida_administrativa import MedidaAdminstrativa
from detransapp.models.modelo import Modelo
from detransapp.models.movimentacao import Movimentacao
from detransapp.models.proprietario import Proprietario
from detransapp.models.regiao import Regiao
from detransapp.models.sistema import Sistema
from detransapp.models.tipo_cancelamento import TipoCancelamento
from detransapp.models.tipo_infracao import TipoInfracao
from detransapp.models.tipo_veiculo import TipoVeiculo
from detransapp.models.veiculo import Veiculo
from detransapp.models.log_importacao import LogImportacao
from detransapp.models.log_sincronizacao import LogSincronizacao
from detransapp.models.config_sinc import ConfigSinc
from detransapp.models.veiculo_editado import VeiculoEditado
from detransapp.models.veiculo_estrangeiro import VeiculoEstrangeiro
from detransapp.models.veiculo_proprietario import VeiculoProprietario
from detransapp.models.DET import Configuracao_DET
